version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    volumes:
      - ftesdata1:/usr/share/elasticsearch/data
    networks:
      - foodtrucks-net
  foodtrucks-frontend:
    image: ft-frontend
    build: ./frontend
    networks:
      - foodtrucks-net
  foodtrucks-backend:
    image: ft-backend
    build: ./backend
    depends_on:
      - es
    networks:
      - foodtrucks-net
  foodtrucks-proxy:
    image: nginx:1.21
    ports:
      - "8080:80"
    depends_on:
      - foodtrucks-backend
      - foodtrucks-frontend
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - foodtrucks-net
volumes:
    ftesdata1:
      driver: local
networks:
  foodtrucks-net:
